// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// Options used:
//   * generate-all
//
// 本地化补丁（仅此文件，为无依赖单文件 rustc guest 可编译）：
//   `wit_bindgen::rt::` -> `crate::wit_bindgen::rt::`
// （Rust 表达式路径不回落本地模块；guest 在 guest_navis_ext.rs 内提供该 shim 模块）。
// 重新生成后需重新应用本补丁。
#[allow(dead_code, clippy::all)]
pub mod navis {
  pub mod ext {
    /// 本包本地共享类型（与 navis:host/types 同名副本）。
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod types {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// 通用载荷：payload / 返回值以 JSON 字符串承载。
      pub type Value = _rt::String;
      /// host 句柄：init 时宿主授予；当前为空资源（空记录，ABI 零参数）。
      #[repr(C)]
      #[derive(Clone, Copy)]
      pub struct HostHandle {
      }
      impl ::core::fmt::Debug for HostHandle {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("HostHandle").finish()
        }
      }

    }

  }
  pub mod host {
    /// 共享类型（组件与宿主共用的值、记录与枚举）。
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod types {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// 通用载荷：payload / 返回值以 JSON 字符串承载。
      pub type Value = _rt::String;
      /// host 句柄：init 时宿主授予；当前为空资源，保留扩展面。
      #[repr(C)]
      #[derive(Clone, Copy)]
      pub struct HostHandle {
      }
      impl ::core::fmt::Debug for HostHandle {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("HostHandle").finish()
        }
      }
      /// 受控操作请求（execute 入参）。
      #[derive(Clone)]
      pub struct OperationRequest {
        pub operation: _rt::String,
        pub target: _rt::String,
        pub params: Option<Value>,
      }
      impl ::core::fmt::Debug for OperationRequest {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("OperationRequest").field("operation", &self.operation).field("target", &self.target).field("params", &self.params).finish()
        }
      }
      /// 受控操作描述（list-operations 返回值）。
      #[derive(Clone)]
      pub struct OperationDescription {
        pub id: _rt::String,
        pub label: _rt::String,
      }
      impl ::core::fmt::Debug for OperationDescription {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("OperationDescription").field("id", &self.id).field("label", &self.label).finish()
        }
      }
      /// 会话快照（context.get-session 返回值）。
      #[derive(Clone)]
      pub struct SessionSnapshot {
        pub id: _rt::String,
        pub title: _rt::String,
      }
      impl ::core::fmt::Debug for SessionSnapshot {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("SessionSnapshot").field("id", &self.id).field("title", &self.title).finish()
        }
      }
      /// 项目快照（context.get-active-project 返回值）。
      #[derive(Clone)]
      pub struct ProjectSnapshot {
        pub id: _rt::String,
        pub name: _rt::String,
      }
      impl ::core::fmt::Debug for ProjectSnapshot {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("ProjectSnapshot").field("id", &self.id).field("name", &self.name).finish()
        }
      }
      /// HTTP 请求（network.fetch 入参）。
      #[derive(Clone)]
      pub struct HttpRequest {
        pub method: _rt::String,
        pub url: _rt::String,
        pub headers: _rt::Vec::<(_rt::String,_rt::String,)>,
        pub body: Option<_rt::String>,
      }
      impl ::core::fmt::Debug for HttpRequest {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("HttpRequest").field("method", &self.method).field("url", &self.url).field("headers", &self.headers).field("body", &self.body).finish()
        }
      }
      /// HTTP 响应（network.fetch 返回值）。
      #[derive(Clone)]
      pub struct HttpResponse {
        pub status: u16,
        pub headers: _rt::Vec::<(_rt::String,_rt::String,)>,
        pub body: Option<_rt::String>,
      }
      impl ::core::fmt::Debug for HttpResponse {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("HttpResponse").field("status", &self.status).field("headers", &self.headers).field("body", &self.body).finish()
        }
      }
      /// 事件订阅句柄（event.subscribe 返回值）。
      #[derive(Clone)]
      pub struct Subscription {
        pub id: _rt::String,
      }
      impl ::core::fmt::Debug for Subscription {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Subscription").field("id", &self.id).finish()
        }
      }
      /// 日志级别（log.write 入参）。
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum LogLevel {
        Trace,
        Debug,
        Info,
        Warn,
        Error,
      }
      impl ::core::fmt::Debug for LogLevel {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            LogLevel::Trace => {
              f.debug_tuple("LogLevel::Trace").finish()
            }
            LogLevel::Debug => {
              f.debug_tuple("LogLevel::Debug").finish()
            }
            LogLevel::Info => {
              f.debug_tuple("LogLevel::Info").finish()
            }
            LogLevel::Warn => {
              f.debug_tuple("LogLevel::Warn").finish()
            }
            LogLevel::Error => {
              f.debug_tuple("LogLevel::Error").finish()
            }
          }
        }
      }

      impl LogLevel{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> LogLevel{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => LogLevel::Trace,
            1 => LogLevel::Debug,
            2 => LogLevel::Info,
            3 => LogLevel::Warn,
            4 => LogLevel::Error,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }


    }

    /// 受控操作执行（门禁在容器，对应 runtime.operation.execute / list）。
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod operation {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type OperationRequest = super::super::super::navis::host::types::OperationRequest;
      pub type OperationDescription = super::super::super::navis::host::types::OperationDescription;
      pub type Value = super::super::super::navis::host::types::Value;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn execute(op: &OperationRequest,) -> Result<Value,_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let super::super::super::navis::host::types::OperationRequest{ operation:operation0, target:target0, params:params0, } = op;
          let vec1 = operation0;
          let ptr1 = vec1.as_ptr().cast::<u8>();
          let len1 = vec1.len();
          let vec2 = target0;
          let ptr2 = vec2.as_ptr().cast::<u8>();
          let len2 = vec2.len();
          let (result4_0,result4_1,result4_2,) = match params0 {
            Some(e) => {
              let vec3 = e;
              let ptr3 = vec3.as_ptr().cast::<u8>();
              let len3 = vec3.len();

              (1i32, ptr3.cast_mut(), len3)
            },
            None => {
              (0i32, ::core::ptr::null_mut(), 0usize)
            },
          };let ptr5 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "navis:host/operation")]
          unsafe extern "C" {
            #[link_name = "execute"]
            fn wit_import6(_: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import6(_: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import6(ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, result4_0, result4_1, result4_2, ptr5);
          let l7 = i32::from(*ptr5.add(0).cast::<u8>());
          let result14 = match l7 {
            0 => {
              let e = {
                let l8 = *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l9 = *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len10 = l9;
                let bytes10 = _rt::Vec::from_raw_parts(l8.cast(), len10, len10);

                _rt::string_lift(bytes10)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l11 = *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l12 = *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len13 = l12;
                let bytes13 = _rt::Vec::from_raw_parts(l11.cast(), len13, len13);

                _rt::string_lift(bytes13)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result14
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn list_operations() -> _rt::Vec::<OperationDescription>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "navis:host/operation")]
          unsafe extern "C" {
            #[link_name = "list-operations"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = *ptr0.add(0).cast::<*mut u8>();
          let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base10 = l2;
          let len10 = l3;
          let mut result10 = _rt::Vec::with_capacity(len10);
          for i in 0..len10 {
            let base = base10.add(i * (4*::core::mem::size_of::<*const u8>()));
            let e10 = {
              let l4 = *base.add(0).cast::<*mut u8>();
              let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len6 = l5;
              let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
              let l7 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l8 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len9 = l8;
              let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

              super::super::super::navis::host::types::OperationDescription{
                id: _rt::string_lift(bytes6),
                label: _rt::string_lift(bytes9),
              }
            };
            result10.push(e10);
          }
          _rt::cabi_dealloc(base10, len10 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          let result11 = result10;
          result11
        }
      }

    }

    /// 日志写入（组件侧受控输出，门禁在容器）。
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod log {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type LogLevel = super::super::super::navis::host::types::LogLevel;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn write(level: LogLevel,message: &str,) -> Result<(),_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = message;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "navis:host/log")]
          unsafe extern "C" {
            #[link_name = "write"]
            fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(level.clone() as i32, ptr0.cast_mut(), len0, ptr1);
          let l3 = i32::from(*ptr1.add(0).cast::<u8>());
          let result7 = match l3 {
            0 => {
              let e = ();
              Ok(e)
            }
            1 => {
              let e = {
                let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l5 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len6 = l5;
                let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

                _rt::string_lift(bytes6)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result7
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod navis {
    pub mod ext {
      /// 扩展组件生命周期（enable/激活/失活）。
      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod lifecycle {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type HostHandle = super::super::super::super::navis::ext::types::HostHandle;
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_init_cabi<T_: Guest>() -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = {
          T_::init(super::super::super::super::navis::ext::types::HostHandle{
          })
        };
        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
        match result0 {
          Ok(_) => { {
            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
          } },
          Err(e) => { {
            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
            let vec2 = (e.into_bytes()).into_boxed_slice();
            let ptr2 = vec2.as_ptr().cast::<u8>();
            let len2 = vec2.len();
            ::core::mem::forget(vec2);
            *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2.cast_mut();
          } },
        };ptr1
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_init<T_: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = i32::from(*arg0.add(0).cast::<u8>());
        match l0 {
          0 => (),
          _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
          },
        }
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_activate_cabi<T_: Guest>() -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result0 = {
        T_::activate()
      };
      let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
      match result0 {
        Ok(_) => { {
          *ptr1.add(0).cast::<u8>() = (0i32) as u8;
        } },
        Err(e) => { {
          *ptr1.add(0).cast::<u8>() = (1i32) as u8;
          let vec2 = (e.into_bytes()).into_boxed_slice();
          let ptr2 = vec2.as_ptr().cast::<u8>();
          let len2 = vec2.len();
          ::core::mem::forget(vec2);
          *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
          *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2.cast_mut();
        } },
      };ptr1
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_activate<T_: Guest>(arg0: *mut u8,) { unsafe {
      let l0 = i32::from(*arg0.add(0).cast::<u8>());
      match l0 {
        0 => (),
        _ => {
          let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l1, l2, 1);
        },
      }
    } }
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_deactivate_cabi<T_: Guest>() -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();let result0 = {
      T_::deactivate()
    };
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result0 {
      Ok(_) => { {
        *ptr1.add(0).cast::<u8>() = (0i32) as u8;
      } },
      Err(e) => { {
        *ptr1.add(0).cast::<u8>() = (1i32) as u8;
        let vec2 = (e.into_bytes()).into_boxed_slice();
        let ptr2 = vec2.as_ptr().cast::<u8>();
        let len2 = vec2.len();
        ::core::mem::forget(vec2);
        *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2.cast_mut();
      } },
    };ptr1
  } }
  #[doc(hidden)]
  #[allow(non_snake_case)]
  pub unsafe fn __post_return_deactivate<T_: Guest>(arg0: *mut u8,) { unsafe {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
      0 => (),
      _ => {
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l1, l2, 1);
      },
    }
  } }
  pub trait Guest {
    #[allow(async_fn_in_trait)]
    fn init(handle: HostHandle,) -> Result<(),_rt::String>;
    #[allow(async_fn_in_trait)]
    fn activate() -> Result<(),_rt::String>;
    #[allow(async_fn_in_trait)]
    fn deactivate() -> Result<(),_rt::String>;
  }
  #[doc(hidden)]

  macro_rules! __export_navis_ext_lifecycle_cabi{
    ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

      #[unsafe(export_name = "navis:ext/lifecycle#init")]
      unsafe extern "C" fn export_init() -> *mut u8 {
        unsafe { $($path_to_types)*::_export_init_cabi::<$ty>() }
      }
      #[unsafe(export_name = "cabi_post_navis:ext/lifecycle#init")]
      unsafe extern "C" fn _post_return_init(arg0: *mut u8,) {
        unsafe { $($path_to_types)*::__post_return_init::<$ty>(arg0) }
      }
      #[unsafe(export_name = "navis:ext/lifecycle#activate")]
      unsafe extern "C" fn export_activate() -> *mut u8 {
        unsafe { $($path_to_types)*::_export_activate_cabi::<$ty>() }
      }
      #[unsafe(export_name = "cabi_post_navis:ext/lifecycle#activate")]
      unsafe extern "C" fn _post_return_activate(arg0: *mut u8,) {
        unsafe { $($path_to_types)*::__post_return_activate::<$ty>(arg0) }
      }
      #[unsafe(export_name = "navis:ext/lifecycle#deactivate")]
      unsafe extern "C" fn export_deactivate() -> *mut u8 {
        unsafe { $($path_to_types)*::_export_deactivate_cabi::<$ty>() }
      }
      #[unsafe(export_name = "cabi_post_navis:ext/lifecycle#deactivate")]
      unsafe extern "C" fn _post_return_deactivate(arg0: *mut u8,) {
        unsafe { $($path_to_types)*::__post_return_deactivate::<$ty>(arg0) }
      }
    };);
  }
  #[doc(hidden)]
  pub(crate) use __export_navis_ext_lifecycle_cabi;

  #[cfg_attr(target_pointer_width="64", repr(align(8)))]
  #[cfg_attr(target_pointer_width="32", repr(align(4)))]
  struct _RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
  static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);

}

/// 扩展组件消息处理（宿主 / 其他组件消息）。
#[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
pub mod message {
  #[used]
  #[doc(hidden)]
  static __FORCE_SECTION_REF: fn() =
  super::super::super::super::__link_custom_section_describing_imports;
  
  use super::super::super::super::_rt;
  pub type Value = super::super::super::super::navis::ext::types::Value;
  #[doc(hidden)]
  #[allow(non_snake_case, unused_unsafe)]
  pub unsafe fn _export_handle_cabi<T_: Guest>(arg0: *mut u8,arg1: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
  _rt::run_ctors_once();let result1 = {
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T_::handle(_rt::string_lift(bytes0))
  };
  let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
  match result1 {
    Ok(e) => { {
      *ptr2.add(0).cast::<u8>() = (0i32) as u8;
      let vec3 = (e.into_bytes()).into_boxed_slice();
      let ptr3 = vec3.as_ptr().cast::<u8>();
      let len3 = vec3.len();
      ::core::mem::forget(vec3);
      *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
      *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3.cast_mut();
    } },
    Err(e) => { {
      *ptr2.add(0).cast::<u8>() = (1i32) as u8;
      let vec4 = (e.into_bytes()).into_boxed_slice();
      let ptr4 = vec4.as_ptr().cast::<u8>();
      let len4 = vec4.len();
      ::core::mem::forget(vec4);
      *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
      *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
    } },
  };ptr2
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_handle<T_: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l1, l2, 1);
    },
    _ => {
      let l3 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l4 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l3, l4, 1);
    },
  }
} }
pub trait Guest {
  #[allow(async_fn_in_trait)]
  fn handle(payload: Value,) -> Result<Value,_rt::String>;
}
#[doc(hidden)]

macro_rules! __export_navis_ext_message_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "navis:ext/message#handle")]
    unsafe extern "C" fn export_handle(arg0: *mut u8,arg1: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_handle_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "cabi_post_navis:ext/message#handle")]
    unsafe extern "C" fn _post_return_handle(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_handle::<$ty>(arg0) }
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_navis_ext_message_cabi;

#[cfg_attr(target_pointer_width="64", repr(align(8)))]
#[cfg_attr(target_pointer_width="32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);

}

}
}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  
  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    crate::wit_bindgen::rt::run_ctors_once();
  }
  extern crate alloc as alloc_crate;
  pub use alloc_crate::alloc;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_guest_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::navis::ext::lifecycle::__export_navis_ext_lifecycle_cabi!($ty with_types_in $($path_to_types_root)*::exports::navis::ext::lifecycle);
  $($path_to_types_root)*::exports::navis::ext::message::__export_navis_ext_message_cabi!($ty with_types_in $($path_to_types_root)*::exports::navis::ext::message);
  )
}
#[doc(inline)]
pub(crate) use __export_guest_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.57.1:navis:ext:guest:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1123] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe7\x07\x01A\x02\x01\
A\x12\x01B\x18\x01s\x04\0\x05value\x03\0\0\x01r\0\x04\0\x0bhost-handle\x03\0\x02\
\x01k\x01\x01r\x03\x09operations\x06targets\x06params\x04\x04\0\x11operation-req\
uest\x03\0\x05\x01r\x02\x02ids\x05labels\x04\0\x15operation-description\x03\0\x07\
\x01r\x02\x02ids\x05titles\x04\0\x10session-snapshot\x03\0\x09\x01r\x02\x02ids\x04\
names\x04\0\x10project-snapshot\x03\0\x0b\x01o\x02ss\x01p\x0d\x01ks\x01r\x04\x06\
methods\x03urls\x07headers\x0e\x04body\x0f\x04\0\x0chttp-request\x03\0\x10\x01r\x03\
\x06status{\x07headers\x0e\x04body\x0f\x04\0\x0dhttp-response\x03\0\x12\x01r\x01\
\x02ids\x04\0\x0csubscription\x03\0\x14\x01m\x05\x05trace\x05debug\x04info\x04wa\
rn\x05error\x04\0\x09log-level\x03\0\x16\x03\0\x10navis:host/types\x05\0\x02\x03\
\0\0\x11operation-request\x02\x03\0\0\x15operation-description\x02\x03\0\0\x05va\
lue\x01B\x0c\x02\x03\x02\x01\x01\x04\0\x11operation-request\x03\0\0\x02\x03\x02\x01\
\x02\x04\0\x15operation-description\x03\0\x02\x02\x03\x02\x01\x03\x04\0\x05value\
\x03\0\x04\x01j\x01\x05\x01s\x01@\x01\x02op\x01\0\x06\x04\0\x07execute\x01\x07\x01\
p\x03\x01@\0\0\x08\x04\0\x0flist-operations\x01\x09\x03\0\x14navis:host/operatio\
n\x05\x04\x02\x03\0\0\x09log-level\x01B\x05\x02\x03\x02\x01\x05\x04\0\x09log-lev\
el\x03\0\0\x01j\0\x01s\x01@\x02\x05level\x01\x07messages\0\x02\x04\0\x05write\x01\
\x03\x03\0\x0enavis:host/log\x05\x06\x01B\x04\x01s\x04\0\x05value\x03\0\0\x01r\0\
\x04\0\x0bhost-handle\x03\0\x02\x03\0\x0fnavis:ext/types\x05\x07\x02\x03\0\x03\x0b\
host-handle\x01B\x08\x02\x03\x02\x01\x08\x04\0\x0bhost-handle\x03\0\0\x01j\0\x01\
s\x01@\x01\x06handle\x01\0\x02\x04\0\x04init\x01\x03\x01@\0\0\x02\x04\0\x08activ\
ate\x01\x04\x04\0\x0adeactivate\x01\x04\x04\0\x13navis:ext/lifecycle\x05\x09\x02\
\x03\0\x03\x05value\x01B\x05\x02\x03\x02\x01\x0a\x04\0\x05value\x03\0\0\x01j\x01\
\x01\x01s\x01@\x01\x07payload\x01\0\x02\x04\0\x06handle\x01\x03\x04\0\x11navis:e\
xt/message\x05\x0b\x04\0\x0fnavis:ext/guest\x04\0\x0b\x0b\x01\0\x05guest\x03\0\0\
\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.247.0\x10wit-bind\
gen-rust\x060.57.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  crate::wit_bindgen::rt::maybe_link_cabi_realloc();
}

